# Generated by Django 4.1 on 2022-08-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopaciente',
            name='comentario',
            field=models.TextField(default='Hola'),
            preserve_default=False,
        ),
    ]
