# Generated by Django 4.1 on 2022-08-27 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliar',
            name='usuario',
            field=models.OneToOneField(blank=True, limit_choices_to={'groups': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_auxiliar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.OneToOneField(blank=True, limit_choices_to={'groups': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalsalud',
            name='usuario',
            field=models.OneToOneField(blank=True, limit_choices_to={'groups': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_p_salud', to=settings.AUTH_USER_MODEL),
        ),
    ]
