# Generated by Django 4.1 on 2022-08-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_usuariopaciente_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopaciente',
            name='comentario',
        ),
    ]
