# Generated by Django 4.1 on 2022-08-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_auxiliar_usuario_alter_paciente_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalsalud',
            name='registro',
            field=models.FileField(blank=True, null=True, upload_to='hospital/registros/'),
        ),
    ]
