# Generated by Django 4.1 on 2022-08-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_personalsalud_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
    ]
