# Generated by Django 4.1 on 2022-08-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_usuariopaciente_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalsalud',
            name='registro',
            field=models.FileField(upload_to='hospital/registros/{usuario}'),
        ),
    ]
